FROM envoyproxy/envoy-dev:latest

RUN apt-get update && \
    apt-get install gettext -y

COPY ./envoy.yaml /tmpl/envoy.yaml.tmpl
COPY ./docker-entrypoint.sh /

RUN chmod 500 /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]