version: '3.2'
services:
  web:
    image: nginx
    restart: always
    container_name: 'dgraph-proxy'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/:ro
    ports:
      - '80:80'

  zero:
    image: dgraph/dgraph:latest
    container_name: 'dgraph-zero'
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: always
    command: dgraph zero --my=zero:5080

  alpha:
    image: dgraph/dgraph:latest
    container_name: 'dgraph-alpha'
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: always
    command: dgraph alpha --my=alpha:7080 --zero=zero:5080 --whitelist 0.0.0.0/0

  ratel:
    image: dgraph/dgraph:latest
    container_name: 'dgraph-ratel'
    ports:
      - 8000:8000
    command: dgraph-ratel
